### Teste do Serviço A - Envio de CEP válido
POST http://localhost:8081/consulta
Content-Type: application/json

{    "cep": "01001000"}

### Teste do Serviço A - Envio de CEP inválido
POST http://localhost:8081/consulta
Content-Type: application/json

{    "cep": "123"}

### Teste do Serviço A - Envio de CEP inválido
POST http://localhost:8081/consulta
Content-Type: application/json

{    "cep": "1234A678"}

### Teste do Serviço A - Envio de CEP inexistente
POST http://localhost:8081/consulta
Content-Type: application/json

{    "cep": "12345678"}
