receivers:
  zipkin:
    endpoint: "0.0.0.0:9411"

exporters:
  zipkin:
    endpoint: "http://zipkin:9411/api/v2/spans"

service:
  pipelines:
    traces:
      receivers: [zipkin]
      exporters: [zipkin]
